import subprocess
import os
from pathlib import Path
import tempfile

class AgentSecuritySimulator:
    """Simule un agent IA générant du code et un scanner vérifiant la sécurité."""
    
    def __init__(self, work_dir: Path):
        self.work_dir = work_dir

    def simulate_agent_action(self, create_secret: bool):
        """L'agent IA écrit un fichier. Parfois, il fait une erreur de sécurité."""
        file_path = self.work_dir / "generated_config.py"
        content = "# Generated by AI Agent\n"
        if create_secret:
            content += "API_KEY = 'AKIAEXAMPLE1234567890' # Erreur de l'agent\n"
        else:
            content += "API_KEY = 'safe_value_without_entropy_risk'\n"
        
        file_path.write_text(content)
        print(f"[Agent] Fichier généré : {file_path.name}")

    def run_security_audit(self) -> None:
        """Lance Gyleaks pour vérifier l'action de l'agent."""
        print("[Audit] Lancement du scan Gyleaks...")
        cmd = ["gitleaks", "detect", "--source", str(self.work_dir), "--report-path", "report.json"]
        
        try:
            # On capture la sortie pour ne pas polluer la console de l'agent
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            print("[Audit] Résultat : Aucun secret trouvé.")
        except subprocess.CalledProcessError as e:
            print("[Audit] ALERTE : Secret détecté dans le code généré par l'agent !")
            print(f"[Audit] Détails du rapport disponibles dans report.json")

def main():
    # Création d'un environnement temporaire pour le test
    with tempfile.TemporaryDirectory() as tmp_dir:
        workspace = Path(tmp_dir)
        simulator = AgentSecuritySimulator(workspace)

        print("--- Scénario 1: Agent bienveillant ---")
        simulator.simulate_agent_action(create_secret=False)
        simulator.run_security_audit()

        print("\n--- Scénario 2: Agent négligent (Fuite de clé) ---")
        simulator.simulate_agent_action(create_secret=True)
        simulator.run_security_audit()

if __name__ == "__main__":
    main